### ISSUE TITLE
Weapon damage research not correctly applying to titanium gun turrets

### ISSUE THREAD

**Issue by ryanalbosta** [jimmyjon711/FactorioExtended-Plus-Weaponry#14]
It seems like the weapons damage research option doesn't apply correctly to the upgraded gun turrets, meaning normal default gun turrets actually outscale the titanium ones lategame. The buff should be applied to both the magazine (potentially after the damage double for titanium turrets, it's currently before) and also to the turret itself, as it does for the vanilla gun turrets.

Ex: research tier 1 yields +10% magazine and +10% turret damage, meaning handheld weaponry does 1.1x damage but turrets do 1.1x1.1 damage, etc. 

My change recommendation:
- Turret 2.0 on research tier 1 with yellow ammo ---> damage = (5*2)*(1 + 0.1 ammo bonus)*(1 + 
   0.1 turret bonus)

Current situation: 
- Turret 2.0 on research tier 1 with yellow ammo ---> damage = 5*(2 + 0.1 ammo bonus)

- Turret 1.0 on research tier 1 with yellow ammo  ---> damage = 5*(1 + 0.1 ammo bonus)*(1 + 0.1 
   turret bonus)

Really love the mods, thanks for the development!

**Comment by billbo99** [comment]
Starting a new game with 0.18.30 and entering /cheat on the console to research all the way up to infiniate research tech then plotting out the numbers.

Phyiscal protectile damage 6
Weapon shootiung speed 6

You can see from the below the mk2 Turrets shoot twice as fast as mk1 turrets,  and do more damage per shot per tier of ammo. 

Turret mk1
- Yellow - 5+32.7 Physical,   10+15 shots / second
- Red - 8+52.32 Physical,   10+15 shots / second
- Blue - 16+105 Physical,   10+15 shots / second
- Green - 24+157 Physical,   10+15 shots / second

Turret mk2
- Yellow - 7.5+49.05 Physical,   20+30 shots / second
- Red - 12+78.48 Physical,   20+30 shots / second
- Blue - 24+157 Physical,   20+30 shots / second
- Green - 36+235 Physical,   20+30 shots / second
