### ISSUE TITLE
0.18.17 fails to load mod

### ISSUE THREAD

**Issue by RandomWolf** [jimmyjon711/FactorioExtended-Plus-Weaponry#15]
In the current version of the game, Factorio 0.18.17, the mod fails to load during startup.
The error message reads:
`The given sprite rectangle (left_top=273x0, right_bottom=312x60) is outside the actual sprite size (left_top=0x0, right_bottom=304x124).: __FactorioExtended-Plus-Weaponry__/graphics/entity/iron-gate/gate-vertical.png
`

**Comment by jimmyjon711** [comment]
I do not think that there is a problem, I was able to load all the update to date mods in 0.18.17. Do you have others mods installed that could be causing this problem?

**Comment by RandomWolf** [comment]
Ah yes, after disabling and enabling mods one after another, I found that _Dectorio 0.10.5_ somehow messed with it. I disabled it and now it boots back up. Thank you for your help!
