### ISSUE TITLE
Laser Turret Mk2 Range is short

### ISSUE THREAD

**Issue by SatanicPotatoes** [jimmyjon711/FactorioExtended-Plus-Weaponry#2]
Range on Laser Turret Mk2 is bumped down to 24 instead of its normal 48.  As the biters now spawn right up to your base was hoping you could bump it up to atleast 36 if not back to normal 48

**Comment by jimmyjon711** [comment]
@SatanicPotatoes yes this will be put back to 48 range and damage back to what its supposed to be
