### ISSUE TITLE
Laser turret MK 2 low power

### ISSUE THREAD

**Issue by mrkrause1** [jimmyjon711/FactorioExtended-Plus-Weaponry#3]
When firing the turret MK 2 switches between full powered and low power multiple times a second. I have more than a gigawatt of extra power available for them. There range is also reduced to about 75% of full distance. I am playing vanilla except for the factorio extend mods. I can send a save file and a mod list if you want.

**Comment by jimmyjon711** [comment]
I will look into this, I do know they are kinda funky. Just have not had alot of time lately

**Comment by dfinton** [comment]
Can confirm I've seen this issue as well. They will fire at full distance (the laser animation makes it all the way to their target) but the laser does no damage. They will draw power while doing this which led to a brownout in my base after my backup accumulators were drained. The laser "flickers" as well. I think this is related to the laser cannon/oil processing update a month and a half ago.

**Comment by maaker48** [comment]
@jimmyjon711  
At line 582 
from file
FactorioExtended-Plus-Weaponry_0.2.2\FactorioExtended-Plus-Weaponry_0.2.2\prototypes\entity\entity-weapons.lua

The range of the attack annimation is on 36, but the attack "damage range" is on 24(@582)
So if you change that it will fix this problem with the range

gz 
MaaKer48

**Comment by DanielNagy** [comment]
https://github.com/jimmyjon711/FactorioExtended-Plus-Weaponry/pull/7 contains the fix. Please review and merge
