### ISSUE TITLE
Gun Turret MK2 damage

### ISSUE THREAD

**Issue by Tempuser8734** [jimmyjon711/FactorioExtended-Plus-Weaponry#4]
There is fixed damage bonus with mk2 turret. But for unknown reason the actual damage values are lesser than vanilla turret, especially when some projectile damage technologies were unlocked.
It results in much higher ammo consumption but is offset by shooting speed and higher range but in my opinion still not worth to upgrade all your cheap turrets.

**Comment by billbo99** [comment]
I belive I have fixed this .. #8 .. each turret needs its own reseaerch bonus for "turret-attack"

**Comment by billbo99** [comment]
Fixed
