### ISSUE TITLE
Fails to load with sound issue in 0.18.2

### ISSUE THREAD

**Issue by NIronwolf** [jimmyjon711/FactorioExtended-Plus-Weaponry#9]
Mod fails to load under v0.18.2 with the following error:

1.542 Error ModManager.cpp:1385: Failed to load mod "FactorioExtended-Plus-Weaponry": __FactorioExtended-Plus-Weaponry__/data.lua:5: ...ded-Plus-Weaponry__/prototypes/entity/entity-weapons.lua:444: attempt to call global 'make_heavy_gunshot_sounds' (a nil value)
stack traceback:
	...ded-Plus-Weaponry__/prototypes/entity/entity-weapons.lua:444: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Weaponry__/data.lua:5: in main chunk
stack traceback:
	[C]: in function 'require'
	__FactorioExtended-Plus-Weaponry__/data.lua:5: in main chunk

It looks like the sound updates to this version have broken things.

**Comment by billbo99** [comment]
Noted, will be fixed in next release
